print("Welcome to the tip calculator!")
bill = float(input("What was the total bill?: $"))
tip = float(input("How much tip would you like to give? 10, 12, or 15?: "))
no_of_splits = int(input("How many people to split the bill?: "))
print(f"Each person should pay: ${round(bill * (1 + (tip / 100)) / no_of_splits, 2)}")